### ISSUE TITLE
[JOSS REVIEW] how to create a problem + list of distributed problems?

### ISSUE THREAD

**Issue by zingale** [enzo-project/enzo-dev#106]
There are a lot of problem setups in `enzo-dev/run`, but I can't seem to find descriptions of them in the docs.  It would be good to have a list of all of these problems with a 1-2 sentence desciption of them.

Also, I can't seem to find instructions on how to add a problem to enzo.  For instance, if I wanted to add a Rayleigh-Taylor instability problem, it is not clear how I would start.

**Comment by zingale** [comment]
JOSS Review: https://github.com/openjournals/joss-reviews/issues/1636

**Comment by bwoshea** [comment]
@zingale this is now addressed in PR #118 .  One issue with documenting every problem in the run/ directory is some subdirectories have many variants of the same problem (e.g., shock tubes, I-front propagation, etc.), and the run/ directory gets fairly regularly updated.  It may make more sense to have documentation of each of the top-level subdirectories within the run/ directory, as well as highlighting a few of the standard/more interesting test problems, and then ensure that the parameter file for each test problem contains an explanation of what it's testing.  That would help with documentation in some ways - i.e., when people put new tests in, all they have to do is make sure the parameter file has comments rather than update both the run/ directory and the documentation.  What do you think?

**Comment by zingale** [comment]
yes, I think that's a good idea.

**Comment by zingale** [comment]
this looks like a great set of docs.
